// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MHcpp1
NumericMatrix MHcpp1(int B, double sd);
RcppExport SEXP _introRcppMetropolis_MHcpp1(SEXP BSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(MHcpp1(B, sd));
    return rcpp_result_gen;
END_RCPP
}
// MHcpp2
NumericMatrix MHcpp2(int B, double sd, int burn, int thin);
RcppExport SEXP _introRcppMetropolis_MHcpp2(SEXP BSEXP, SEXP sdSEXP, SEXP burnSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(MHcpp2(B, sd, burn, thin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_introRcppMetropolis_MHcpp1", (DL_FUNC) &_introRcppMetropolis_MHcpp1, 2},
    {"_introRcppMetropolis_MHcpp2", (DL_FUNC) &_introRcppMetropolis_MHcpp2, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_introRcppMetropolis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
