# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MHcpp1 <- function(B, sd) {
    .Call(`_introRcppMetropolis_MHcpp1`, B, sd)
}

MHcpp2 <- function(B, sd, burn = 0L, thin = 1L) {
    .Call(`_introRcppMetropolis_MHcpp2`, B, sd, burn, thin)
}

